import assert from 'node:assert/strict';
import {readFile, readdir} from 'node:fs/promises';
import test from 'node:test';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {sha256Hex} from '../src/integrity.mjs';
import {assertSafeMergedManifest} from '../tools/check-android-manifest.mjs';
import {buildFixtures} from '../tools/generate-fixtures.mjs';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixtureDir = path.join(projectRoot, 'fixtures', 'synthetic');
// Mozilla's published MPL-2.0 text, normalized only by removing its incidental
// trailing space on section 1.7 so repository-wide whitespace checks stay green.
const NORMALIZED_MPL_2_SHA256 =
  '1f256ecad192880510e84ad60474eab7589218784b9a50bc7ceee34c2b91f1d5';

async function sourceModules(directory, found = []) {
  for (const entry of await readdir(directory, {withFileTypes: true})) {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await sourceModules(full, found);
    } else if (entry.name.endsWith('.mjs') || entry.name.endsWith('.js')) {
      found.push(full);
    }
  }
  return found;
}

async function readJson(relativePath) {
  return JSON.parse(await readFile(path.join(projectRoot, relativePath), 'utf8'));
}

test('the shared SHA-256 matches standard vectors and byte-offset views', () => {
  const encode = text => new TextEncoder().encode(text);
  assert.equal(
    sha256Hex(new Uint8Array(0)),
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  );
  assert.equal(
    sha256Hex(encode('abc')),
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
  );
  assert.equal(
    sha256Hex(encode('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')),
    '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'
  );

  const offset = encode('_abc_').subarray(1, 4);
  assert.equal(
    sha256Hex(offset),
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    'a Uint8Array view must hash only its own byteOffset/byteLength'
  );
});

/**
 * Strips `constraints { ... }` blocks out of a Gradle build file.
 *
 * A constraint pins the version of something already in the dependency graph. It
 * uses the same `implementation("group:artifact:version")` syntax as a real
 * declaration, so anything reading declarations by pattern sees a version pin as
 * a newly adopted component.
 */
function withoutConstraintBlocks(source) {
  const blockStart = /\bconstraints\s*\{/g;
  let result = '';
  let index = 0;
  let match;

  while ((match = blockStart.exec(source)) !== null) {
    result += source.slice(index, match.index);

    // Walk the braces rather than matching to the next `}`, so a nested block
    // cannot end the skip early.
    let depth = 0;
    let cursor = match.index + match[0].length - 1;
    for (; cursor < source.length; cursor += 1) {
      if (source[cursor] === '{') {
        depth += 1;
      } else if (source[cursor] === '}') {
        depth -= 1;
        if (depth === 0) {
          cursor += 1;
          break;
        }
      }
    }

    index = cursor;
    blockStart.lastIndex = cursor;
  }

  return result + source.slice(index);
}

test('every committed fixture is generated by this project and hash-stable', async () => {
  const manifest = await readJson('fixtures/synthetic/manifest.json');
  assert.equal(manifest.origin, 'generated');
  assert.equal(manifest.thirdPartyMaterial, 'none');
  assert.equal(manifest.containsRealFlightData, false);

  const onDisk = (await readdir(fixtureDir)).filter(name => name !== 'manifest.json');
  assert.deepEqual(
    onDisk.sort(),
    manifest.fixtures.map(fixture => fixture.file).sort(),
    'fixtures/ must contain exactly the generated files listed in the manifest'
  );

  for (const fixture of manifest.fixtures) {
    const bytes = await readFile(path.join(fixtureDir, fixture.file));

    // A checkout that rewrote line endings shows up as a length inflated by
    // exactly the number of newlines. Say so, rather than leaving someone to
    // work out why a committed file changed size on its own.
    if (bytes.length !== fixture.byteLength) {
      const newlines = bytes.filter(byte => byte === 0x0a).length;
      const mangled = bytes.length - fixture.byteLength === newlines;
      assert.fail(
        `${fixture.file} is ${bytes.length} bytes, expected ${fixture.byteLength}` +
        (mangled
          ? '. The difference equals its newline count, so the checkout converted ' +
            'LF to CRLF — .gitattributes should mark logs as binary. Restore with: ' +
            'git rm --cached -r . && git reset --hard'
          : '.')
      );
    }

    assert.equal(sha256Hex(bytes), fixture.sha256, `${fixture.file} hash changed`);
  }
});

test('regenerating the corpus reproduces the committed bytes exactly', async () => {
  const committed = await readJson('fixtures/synthetic/manifest.json');

  // Built in memory rather than written to disk. Calling generateFixtures() here
  // would rewrite the fixtures and silently repair a mangled checkout, hiding
  // the corruption from the test above depending on which ran first.
  const regenerated = buildFixtures().map(fixture => ({
    file: fixture.file,
    description: fixture.description,
    byteLength: fixture.bytes.length,
    sha256: sha256Hex(fixture.bytes)
  }));

  assert.deepEqual(
    regenerated,
    committed.fixtures,
    'fixture generation must be deterministic; provenance is proven by reproduction'
  );
});

test('the shared engine contains no Node-only APIs', async () => {
  const sourceRoot = path.join(projectRoot, 'src');
  for (const file of await sourceModules(sourceRoot)) {
    const source = await readFile(file, 'utf8');
    const relative = path.relative(projectRoot, file);
    const code = source
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\/\/.*$/gm, '');
    assert.doesNotMatch(
      code,
      /(?:from\s+|import\s*\()(['"])node:/,
      `${relative} imports a Node-only module but src/ ships in a browser and Android WebView`
    );
    assert.doesNotMatch(
      code,
      /\bBuffer\s*[.(]/,
      `${relative} uses Buffer but src/ must accept browser-native Uint8Array values`
    );
  }
});

test('nothing third-party is bundled without a notice', async () => {
  const decision = await readJson('config/parser-engine-decision.json');
  const notices = await readFile(path.join(projectRoot, 'THIRD_PARTY_NOTICES.md'), 'utf8');
  const manifest = await readJson('package.json');

  const bundled = [
    ...Object.keys(manifest.dependencies ?? {}),
    ...Object.keys(manifest.devDependencies ?? {}),
    ...Object.keys(manifest.optionalDependencies ?? {}),
    ...Object.keys(manifest.peerDependencies ?? {}),
    ...(Array.isArray(manifest.bundledDependencies) ? manifest.bundledDependencies : []),
    ...(Array.isArray(manifest.bundleDependencies) ? manifest.bundleDependencies : []),
    ...(decision.adopted?.thirdParty ? [decision.adopted.name] : [])
  ];

  for (const component of bundled) {
    assert.ok(
      notices.includes(component),
      `${component} is bundled but has no entry in THIRD_PARTY_NOTICES.md`
    );
  }

  if (bundled.length === 0) {
    assert.match(
      notices,
      /No third-party/i,
      'with nothing bundled, the notices file must say so plainly'
    );
  }
});

test('every artifact the APK carries is recorded in the notices', async () => {
  // The declared list is not the shipped list. One `implementation` line pulls in
  // twenty-seven other artifacts from three further copyright holders, and
  // Apache-2.0 attribution attaches to what is distributed. So this checks the
  // resolved classpath, recorded by `gradlew :app:recordShippingDependencies`.
  const snapshot = await readJson('android/shipping-dependencies.json');
  const notices = await readFile(path.join(projectRoot, 'THIRD_PARTY_NOTICES.md'), 'utf8');

  assert.ok(
    snapshot.components.length > 0,
    'the snapshot must list what ships; an empty one would pass this test vacuously'
  );

  // Whole lines, not `includes`. A substring match greens the moment a
  // coordinate appears anywhere in the file — inside a sentence, inside a longer
  // coordinate — without any obligation having been met.
  const listed = new Set(notices.split('\n').map(line => line.trim()));

  for (const component of snapshot.components) {
    assert.ok(
      listed.has(component),
      `${component} ships in the APK but has no entry in THIRD_PARTY_NOTICES.md`
    );
  }
});

test('the shipping snapshot still covers what the build file declares', async () => {
  // Guards the snapshot against going stale: adding a dependency without
  // regenerating it would otherwise leave the notices checked against an old,
  // passing list.
  const gradle = await readFile(
    path.join(projectRoot, 'android', 'app', 'build.gradle.kts'), 'utf8'
  );
  const snapshot = await readJson('android/shipping-dependencies.json');

  // A `constraints` block pins the version of something already in the graph. It
  // declares nothing, and reading one as a dependency is how this test used to
  // report a version pin as an unattributed component.
  const declarations = withoutConstraintBlocks(gradle);
  const declared = [...declarations.matchAll(
    /implementation\("([^:"]+):([^:"]+):([^"]+)"\)/g
  )].map(match => `${match[1]}:${match[2]}:${match[3]}`);

  assert.ok(declared.length > 0, 'the pattern must still match how deps are declared');

  const shipped = new Set(snapshot.components);

  for (const coordinate of declared) {
    assert.ok(
      shipped.has(coordinate),
      `${coordinate} is declared at a different coordinate than ` +
        'android/shipping-dependencies.json records; ' +
        'regenerate it with `gradlew :app:recordShippingDependencies`'
    );
  }
});

test('the legal screen is generated from what actually ships', async () => {
  // Same discipline as the fixture corpus: the committed file must be exactly
  // what the generator produces, so it cannot be edited into agreement with a
  // dependency list that has moved on.
  const {renderLegalModule, buildLegalData} = await import('../tools/generate-legal.mjs');
  const committed = await readFile(path.join(projectRoot, 'ui', 'legal-data.mjs'), 'utf8');

  assert.equal(
    renderLegalModule(await buildLegalData()),
    committed,
    'ui/legal-data.mjs is stale; regenerate it with `npm run legal:generate`'
  );
});

test('the Android shell identifies its legal-notice platform exactly', async () => {
  const activity = await readFile(
    path.join(
      projectRoot,
      'android',
      'app',
      'src',
      'main',
      'java',
      'app',
      'rotorlens',
      'MainActivity.java'
    ),
    'utf8'
  );

  assert.match(
    activity,
    /@JavascriptInterface\s+public String platform\(\)\s*\{\s*return "android";\s*\}/,
    'the Android bridge must synchronously return exactly "android" so About & Legal ' +
      'selects the resolved Android Maven inventory'
  );
});

test('every artifact the APK carries is attributed in the legal screen', async () => {
  const snapshot = await readJson('android/shipping-dependencies.json');
  const {LEGAL} = await import('../ui/legal-data.mjs');

  assert.deepEqual(Object.keys(LEGAL.componentsByPlatform).sort(), ['android', 'ios', 'web']);
  assert.deepEqual(LEGAL.componentsByPlatform.ios, [],
    'iOS legal data must not claim Android Maven artifacts');
  assert.deepEqual(LEGAL.componentsByPlatform.web, [],
    'web legal data must not claim Android Maven artifacts');

  const androidComponents = LEGAL.componentsByPlatform.android;
  const attributed = new Set(androidComponents.flatMap(component => component.artifacts));
  for (const component of snapshot.components) {
    assert.ok(
      attributed.has(component),
      `${component} ships but is not attributed in the app's legal screen`
    );
  }

  assert.deepEqual([...attributed].sort(), [...snapshot.components].sort(),
    'Android About & Legal must contain exactly the resolved Maven artifacts');

  for (const component of androidComponents) {
    assert.ok(component.copyright, `${component.holder} must carry a copyright line`);
    assert.ok(component.license, `${component.holder} must name its license`);
  }

  // Apache-2.0 section 4 is the clause that obliges us to hand over the text, so
  // shipping the text without that section would be its own quiet failure.
  const apache = LEGAL.licenseTexts['Apache-2.0'];
  assert.ok(apache, 'the Apache-2.0 text must ship; every bundled component is under it');
  assert.match(apache, /4\. Redistribution/, 'the license text must be the complete one');
  assert.match(apache, /Apache License\s+Version 2\.0, January 2004/);
});

test('the legal screen carries the non-affiliation statement', async () => {
  // Trademark is independent of license. This line is on the pre-submission
  // checklist in docs/LICENSING_AND_STORE_READINESS.md, and it is exactly the
  // kind of sentence that gets tidied away in a redesign.
  const {LEGAL} = await import('../ui/legal-data.mjs');

  assert.match(LEGAL.nonAffiliation, /not affiliated with/i);
  assert.match(LEGAL.nonAffiliation, /Rotorflight/);
  assert.match(LEGAL.nonAffiliation, /Betaflight/);
});

test('RotorLens license, creator, package and source declarations cannot drift', async () => {
  const licenseBytes = await readFile(path.join(projectRoot, 'LICENSE'));
  const license = licenseBytes.toString('utf8');
  const manifest = await readJson('package.json');
  const lock = await readJson('package-lock.json');
  const decision = await readJson('config/parser-engine-decision.json');
  const fixtures = await readJson('fixtures/synthetic/manifest.json');
  const readme = await readFile(path.join(projectRoot, 'README.md'), 'utf8');
  const notices = await readFile(path.join(projectRoot, 'THIRD_PARTY_NOTICES.md'), 'utf8');
  const licensing = await readFile(
    path.join(projectRoot, 'docs', 'LICENSING_AND_STORE_READINESS.md'), 'utf8'
  );
  const architecture = await readFile(
    path.join(projectRoot, 'docs', 'ARCHITECTURE_AND_PROVENANCE.md'), 'utf8'
  );
  const viewerIntegration = await readFile(
    path.join(projectRoot, 'integration', 'rotorflight-blackbox', 'README.md'), 'utf8'
  );
  const viewerPatch = await readFile(
    path.join(
      projectRoot,
      'integration',
      'rotorflight-blackbox',
      '0001-consume-rotorlens-pid-evidence.patch'
    ),
    'utf8'
  );
  const viewerLicense = await readFile(
    path.join(projectRoot, 'integration', 'rotorflight-blackbox', 'LICENSE')
  );
  const {ENGINE} = await import('../src/blackbox/decode.mjs');
  const {LEGAL} = await import('../ui/legal-data.mjs');

  assert.equal(
    sha256Hex(new Uint8Array(licenseBytes)),
    NORMALIZED_MPL_2_SHA256,
    'LICENSE must remain the official MPL-2.0 text (with only documented whitespace normalization)'
  );
  assert.match(license, /^Mozilla Public License Version 2\.0/);
  assert.match(license, /Exhibit A - Source Code Form License Notice/);

  for (const [where, declared] of [
    ['package.json', manifest.license],
    ['package-lock.json', lock.packages[''].license],
    ['parser decision', decision.adopted.license],
    ['decoder runtime', ENGINE.license],
    ['fixture manifest', fixtures.license],
    ['About & Legal', LEGAL.project.license],
    ['About & Legal decoder', LEGAL.engine.license]
  ]) {
    assert.equal(declared, 'MPL-2.0', `${where} drifted from the root license`);
  }

  assert.equal(lock.name, manifest.name);
  assert.equal(lock.version, manifest.version);
  assert.equal(lock.packages[''].name, manifest.name);
  assert.equal(lock.packages[''].version, manifest.version);
  assert.equal(manifest.name, 'rotorlens');
  assert.equal(manifest.author.name, 'Michael Wallace');
  assert.equal(manifest.author.url, 'https://github.com/mbwallace1390');
  const repository = manifest.repository.url.replace(/^git\+/, '').replace(/\.git$/, '');
  assert.equal(LEGAL.project.repository, repository);
  assert.equal(manifest.homepage, `${repository}#readme`);
  assert.equal(manifest.bugs.url, `${repository}/issues`);
  assert.equal(LEGAL.project.creator, 'Michael Wallace');
  assert.match(LEGAL.project.attribution, /originally created by Michael Wallace/);
  assert.equal(LEGAL.project.copyright, 'Copyright (c) 2026 Michael Wallace and contributors');
  assert.equal(LEGAL.engine.copyright, 'Copyright (c) 2026 Michael Wallace');
  assert.equal(manifest.rotorlens.releaseStatus, 'development');
  assert.equal(LEGAL.project.sourceRef, null,
    'an unreleased development build must not fabricate a source tag');
  assert.equal(LEGAL.project.sourceUrl, LEGAL.project.repository);
  assert.match(LEGAL.project.sourceStatus, /Development build 0\.1\.0.*unreleased/);
  assert.equal(LEGAL.licenseTexts['MPL-2.0'], license,
    'the app must ship the same MPL text as the repository');
  assert.match(readme, /originally created by \*\*Michael Wallace\*\*/);
  assert.match(readme, /MPL-2\.0/);
  assert.match(readme, /non-shipping GPL viewer integration patch/);
  assert.doesNotMatch(readme, /\/tree\/v0\.1\.0|\/releases\/tag\/v0\.1\.0/,
    'README must not link a release tag that does not exist');
  assert.match(readme, /former MIT\s+license remain usable\s+under that grant/);
  assert.match(licensing, /former MIT\s+license remain usable under that\s+license/);
  assert.match(notices, /covered by MPL-2\.0/);
  assert.match(notices, /patch is GPL-covered and is not relicensed/);
  assert.match(architecture,
    /0001-consume-rotorlens-pid-evidence\.patch[\s\S]*patch is\s+GPL-covered/);
  assert.match(viewerIntegration, /patch itself is GPL-covered/);
  assert.match(viewerIntegration, /MPL-2\.0 section 3\.3/);
  assert.match(viewerIntegration, /492bee5b5835a2a88ec725489e5e6d4ee52c678f/);
  assert.match(viewerIntegration, /ae1bca03d11a713c19e13d156a27d6591316cf03/);
  assert.doesNotMatch(viewerIntegration, /git checkout codex\/cross-platform-foundation/);
  assert.equal(
    sha256Hex(new Uint8Array(viewerLicense)),
    'e57f1c320b8cf8798a7d2ff83a6f9e06a33a03585f6e065fea97f1d86db84052',
    'the viewer patch boundary must carry the exact pinned GPL text'
  );
  assert.equal(
    sha256Hex(new TextEncoder().encode(viewerPatch)),
    'bb49324ec62e71efc2f877dab3ad4dbd3fc22ddc99fcc26a5de25b47a61aab83',
    'the documented viewer integration patch bytes drifted'
  );
  assert.match(viewerPatch, /RotorLens \(MPL-2\.0\)/);
  assert.match(viewerPatch, /integration remains GPL-covered/);
  assert.match(notices, /propwash[\s\S]*voluntary design credit/i);
  assert.match(architecture, /mechanical_analysis\.js[\s\S]*No viewer reference/);
});

test('the committed Gradle wrapper is the jar Gradle published', async () => {
  // Verified against gradle.org/release-checksums and the checksum served beside
  // the distribution itself, on 2026-08-11. This jar executes on every build,
  // which makes it the one binary here worth more scrutiny than a fixture.
  const publishedWrapperSha256 =
    '7d3a4ac4de1c32b59bc6a4eb8ecb8e612ccd0cf1ae1e99f66902da64df296172';

  const jar = await readFile(
    path.join(projectRoot, 'android', 'gradle', 'wrapper', 'gradle-wrapper.jar')
  );
  assert.equal(
    sha256Hex(new Uint8Array(jar)),
    publishedWrapperSha256,
    'the committed Gradle wrapper is not the published one; do not build with it'
  );

  const notices = await readFile(path.join(projectRoot, 'THIRD_PARTY_NOTICES.md'), 'utf8');
  assert.ok(
    notices.includes(publishedWrapperSha256),
    'the notices must record the hash that was actually verified'
  );

  // Pinning the distribution closes the other half: the wrapper jar is only as
  // trustworthy as the Gradle build it goes on to download and run.
  const properties = await readFile(
    path.join(projectRoot, 'android', 'gradle', 'wrapper', 'gradle-wrapper.properties'), 'utf8'
  );
  assert.match(
    properties,
    /distributionSha256Sum=[0-9a-f]{64}/,
    'the Gradle distribution must be checksum-pinned'
  );
});

test('Gradle verifies every recorded dependency artifact and CI enforces strict mode', async () => {
  const verification = await readFile(
    path.join(projectRoot, 'android', 'gradle', 'verification-metadata.xml'), 'utf8'
  );
  const ci = await readFile(path.join(projectRoot, '.github', 'workflows', 'ci.yml'), 'utf8');

  assert.match(verification, /<verify-metadata>true<\/verify-metadata>/);
  assert.match(verification, /<verify-signatures>false<\/verify-signatures>/);
  assert.doesNotMatch(
    verification,
    /<(?:md5|sha1)\b/,
    'dependency verification must not rely on a collision-broken checksum'
  );

  const artifacts = [...verification.matchAll(
    /<artifact name="([^"]+)">([\s\S]*?)<\/artifact>/g
  )];
  assert.ok(artifacts.length > 0, 'verification metadata must record resolved artifacts');
  for (const [, artifact, checksums] of artifacts) {
    assert.match(
      checksums,
      /<sha256 value="[0-9a-f]{64}"/,
      `${artifact} has no SHA-256 dependency-verification checksum`
    );
  }

  // These three scopes are easy to miss when metadata is bootstrapped from a
  // single assemble task: settings/build plugins, the shipped runtime and tests.
  for (const coordinate of [
    'group="com.android.application" name="com.android.application.gradle.plugin" version="8.13.2"',
    'group="androidx.activity" name="activity" version="1.9.3"',
    'group="junit" name="junit" version="4.13.2"'
  ]) {
    assert.ok(
      verification.includes(coordinate),
      `${coordinate} is missing from dependency-verification metadata`
    );
  }

  assert.match(
    verification,
    /<artifact name="aapt2-8\.13\.2-14304508-linux\.jar">\s*<sha256 value="839609d6d776d6dd60a02aa577d97193ce3e650cf1deaabf062321e23bbd6bf6"/,
    'Ubuntu CI needs the publisher-verified Linux AAPT2 binary in the metadata'
  );
  assert.match(
    verification,
    /<artifact name="guava-parent-33\.3\.1-jre\.pom">\s*<sha256 value="55441db27e8869dfefe053059bdf478bdc7e95585642bf391f0023345fd56287"/,
    'a cold Android configuration needs Guava parent metadata verified'
  );
  assert.match(
    verification,
    /<artifact name="junit-bom-5\.10\.2\.module">\s*<sha256 value="de23b114b3e4119a8fe6eb17bed5a3852816698bace67071579d6d927ebb080a"/,
    'a cold Android configuration needs JUnit module metadata verified'
  );

  assert.match(
    ci,
    /\.\/gradlew --dependency-verification strict\s+assembleDebug lintDebug testDebugUnitTest bundleRelease\s+:app:recordShippingDependencies/,
    'Android CI must fail closed under strict Gradle dependency verification'
  );
  assert.match(
    ci,
    /npm run legal:generate[\s\S]*git diff --exit-code -- android\/shipping-dependencies\.json ui\/legal-data\.mjs/,
    'Android CI must compare resolved dependencies and generated legal data with the checkout'
  );
});

test('CI validates branch pushes without exposing checkout credentials or private caches', async () => {
  const ci = await readFile(path.join(projectRoot, '.github', 'workflows', 'ci.yml'), 'utf8');

  assert.match(
    ci,
    /on:\s*\n\s+push:\s*\n\s+pull_request:\s*\n\s+workflow_dispatch:/,
    'CI must validate ordinary branch pushes and support an explicit manual run'
  );

  const checkoutCount = (ci.match(/uses: actions\/checkout@[0-9a-f]{40}/g) ?? []).length;
  const credentialOptOutCount = (ci.match(/persist-credentials: false/g) ?? []).length;
  assert.ok(checkoutCount > 0, 'CI must check out the repository');
  assert.equal(
    credentialOptOutCount,
    checkoutCount,
    'every checkout must remove its credential before repository code runs'
  );

  assert.match(
    ci,
    /gradle\/actions\/setup-gradle@[0-9a-f]{40}[\s\S]*?cache-provider: basic/,
    'Gradle must use the open GitHub-backed cache provider'
  );
  assert.match(
    ci,
    /runs-on: windows-latest[\s\S]*?npm run check:syntax\s+npm test/,
    'Windows-specific paths must be exercised on a Windows runner'
  );
});

test('the source manifest requests no permissions or network access', async () => {
  const manifest = await readFile(
    path.join(projectRoot, 'android', 'app', 'src', 'main', 'AndroidManifest.xml'), 'utf8'
  );

  // Without INTERNET the app cannot upload a flight. That is a stronger promise
  // than a privacy policy, and it is one line away from being lost.
  assert.ok(
    !/<uses-permission/.test(manifest),
    'a permission was added; if that is intended, update the privacy claims too'
  );
  assert.ok(
    !/android.permission.INTERNET/.test(manifest),
    'RotorLens must not be able to reach the network'
  );
});

test('the merged-manifest gate allows only AndroidX\'s app-local signature permission', () => {
  const generated = `
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <permission
        android:name="app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"
        android:protectionLevel="signature" />
      <uses-permission
        android:name="app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
    </manifest>`;
  assert.deepEqual(
    assertSafeMergedManifest(generated),
    ['app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION']
  );

  const networked = `
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <uses-permission android:name="android.permission.INTERNET" />
    </manifest>`;
  assert.throws(
    () => assertSafeMergedManifest(networked),
    /android\.permission\.INTERNET/
  );

  const missingDeclaration = `
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <uses-permission
        android:name="app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
    </manifest>`;
  assert.throws(
    () => assertSafeMergedManifest(missingDeclaration),
    /protectionLevel="signature"/
  );

  const normalProtection = `
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <permission
        android:protectionLevel="normal"
        android:name="app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
      <uses-permission
        android:name="app.rotorlens.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
    </manifest>`;
  assert.throws(
    () => assertSafeMergedManifest(normalProtection),
    /protectionLevel="signature"/
  );
});

test('the app holds USB host but contains no way to talk to a flight controller', async () => {
  // The manifest declares android.hardware.usb.host and a USB_DEVICE_ATTACHED
  // filter so a board entering mass-storage mode can offer to open RotorLens and
  // save the pilot a step. That grants permission to COMMUNICATE with the device
  // that launched it.
  //
  // "RotorLens never connects to or writes to a flight controller" is in the
  // store listing and in the in-app disclaimer. Before that filter it was true
  // because no USB code existed in the binary; this test is what keeps that the
  // reason, so the claim stays structural rather than becoming a promise. It is
  // the same standard docs/LOG_IMPORT.md sets for any future MSP download:
  // read-only by construction, not by intention.
  const androidRoot = path.join(projectRoot, 'android', 'app', 'src', 'main');
  const manifest = await readFile(path.join(androidRoot, 'AndroidManifest.xml'), 'utf8');

  assert.match(manifest, /android\.hardware\.usb\.host/,
    'the USB host feature is expected here; if it was removed, remove this test with it');
  assert.match(manifest, /USB_DEVICE_ATTACHED/);

  // A feature, never a permission. As <uses-feature> it asks for hardware; as
  // <uses-permission> it would be something else entirely.
  assert.ok(!/<uses-permission/.test(manifest), 'usb.host must stay a feature, not a permission');

  const javaRoot = path.join(androidRoot, 'java', 'app', 'rotorlens');
  const sources = await readdir(javaRoot);
  const forbidden = [
    'UsbManager', 'UsbDeviceConnection', 'UsbEndpoint', 'UsbInterface', 'UsbRequest',
    'openDevice', 'bulkTransfer', 'controlTransfer', 'claimInterface', 'UsbSerial'
  ];

  for (const name of sources.filter(entry => entry.endsWith('.java'))) {
    const source = await readFile(path.join(javaRoot, name), 'utf8');
    // Comments are where this rule is explained, so they are stripped before the
    // search; otherwise the explanation would trip the check it explains.
    const code = source
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\/\/.*$/gm, '');
    for (const token of forbidden) {
      assert.ok(
        !code.includes(token),
        `${name} references ${token}. RotorLens must contain no way to talk to a flight `
          + 'controller; if that is changing deliberately, docs/STORE_LISTING.md and the '
          + 'in-app disclaimer both claim otherwise and must change first.'
      );
    }
  }
});

test('the adopted decoder is ours and lives where the record says it does', async () => {
  const decision = await readJson('config/parser-engine-decision.json');

  assert.equal(decision.adopted.thirdParty, false);
  assert.equal(decision.adopted.license, 'MPL-2.0');
  assert.ok(decision.adopted.conformance.assumptions, 'format assumptions must be documented');

  const {ENGINE} = await import('../src/blackbox/decode.mjs');
  assert.equal(
    ENGINE.name,
    decision.adopted.name,
    'the shipped engine identity must match the decision record'
  );
});

test('every rejected and excluded engine records a verified license', async () => {
  const decision = await readJson('config/parser-engine-decision.json');

  for (const entry of [...decision.rejected, ...decision.excluded]) {
    assert.ok(entry.name && entry.repository && entry.license && entry.reason);
    assert.ok(entry.verifiedAt, `${entry.name} must record when its license was checked`);
  }

  for (const entry of decision.excluded) {
    assert.match(entry.license, /GPL/, 'the excluded list is for copyleft engines');
  }
});
